### ISSUE TITLE
Make a release (0.4)

### ISSUE THREAD

**Issue by jasonhan-vassar** [fourmolu/fourmolu#104]
Hi, so I'm using the `fourmolu` binary via stdin and I have a config file at `~/.config`. When I run something like `cat /path/to/file.hs | fourmolu`, the first line of output is "Loaded config from: ~/.config/fourmolu.yaml", followed by the rest of the stdout. This extra output messes with my program; is there an option to silence this? Thanks for reading.

**Comment by kukimik** [comment]
I thought  this was fixed in #42?

**Comment by georgefst** [comment]
> I thought this was fixed in #42?

Yeah, I think it was. The problem here is that we haven't made a release in a while. Ormolu actually made a major release today, so it would be a good time to merge that in as well as reviewing current PRs.

I've just really been struggling for time recently. I'm happy for @kukimik and/or @brandonchinn178 to take that work on if you're confident and have the time. Otherwise I'll hopefully get there in the next few weeks.

**Comment by brandonchinn178** [comment]
i have a pr up to get ghc 9 support (which ormolu just merged today). hopefully i can finish that up next week and we can make a release?

**Comment by georgefst** [comment]
Great. Shall we aim to make a release by, say, next Sunday evening (UTC)? I'll see how many open PRs I can get to before then.

That's not a *hard* deadline. But if we can get Ormolu 0.2 and GHC 9.0 in, I think we should be good to go. Priority is just to get something out the door. #42 and #64 are both pretty important.

**Comment by georgefst** [comment]
Sorry for somewhat hijacking your issue @jasonhan-vassar. May as well continue this discussion here now.

**Comment by brandonchinn178** [comment]
GHC 9 support (and other ormolu updates) here: https://github.com/fourmolu/fourmolu/pull/106

**Comment by georgefst** [comment]
> #42 and #64 are both pretty important.

Due to this, I'd really like to get a release out ASAP, and consider it to only be blocked on #106. Though #111 would also be nice if I find the time.

Then we can take the time to review all the open PRs properly, and prepare for the next release after this to be a substantial one (perhaps even call it 1.0, though it maybe feels weird to get to that milestone before Ormolu does).

**Comment by brandonchinn178** [comment]
@georgefst should we do this release soon, with #106 merged?

**Comment by georgefst** [comment]
Yep, I'm planning to get it done in the next hour. Then in the coming days I'll comment on #112 about where we go from here.
