### ISSUE TITLE
Merge pull requests

### ISSUE THREAD

**Issue by pepeiborra** [fourmolu/fourmolu#112]
There are 12 open PRs right now, and at least 4 of them have a green light meaning all the tests pass and there are no merge conflicts. The oldest one is 3 months old and the other ones are all >1 month old. (#108, #103, #102, #101)

My concern is that the maintainers are no longer able to work on fourmolu. Maybe it would be a good idea to issue a call for new maintainers?

**Comment by jneira** [comment]
Pinging @georgefst, as they have been merge last prs here

**Comment by georgefst** [comment]
Thanks @jneira. I have seen this, and started writing up a full response on Wednesday, but haven't yet had the time to finish it. Which, actually, probably tells you most of what you need to know.

The tl;dr will be that I'm sufficiently motivated and available to just about keep the project ticking over, but we could really do with a few more pairs of hands.

**Comment by georgefst** [comment]
Many open PRs are effectively blocked due to the lack of testing: see https://github.com/fourmolu/fourmolu/issues/49#issuecomment-955271097.

**Comment by georgefst** [comment]
As many of you will have noticed, @brandonchinn178 has taken over much of the day-to-day maintenance of the project. I'm still keeping an eye on things (and to a lesser extent, so is @parsonsmatt), and commenting on opened issues and PRs where I feel I have useful input, but I expect I'll mostly continue to struggle to find the time to do any implementation work or detailed code reviews.

Anyway, thanks largely to Brandon's hard work, we're in much better shape than when this issue was opened. In particular, we have implemented a solution to the testing problem in https://github.com/fourmolu/fourmolu/pull/169. Some PRs which were blocked on that unfortunately remain unmerged, because their original authors haven't been able to get back to them yet. But if anyone here cares a lot about any particular PR, feel free to pick it up and carry on the work yourself. Brandon has even left a helpful comment on each one about what needs to be done to bring the work up to date and add tests.

# Some background

(This was going to form the basis of a mea culpa of sorts, alluded to in https://github.com/fourmolu/fourmolu/issues/112#issuecomment-927383812, but a lot of what I was going to say isn't relevant 10 months on.)

We've seen a lot of Haskell formatters come and go. For various reasons, it has proved a surprisingly difficult problem, with several tools only covering a small subset of the language, or falling out of maintenance remarkably quickly. Ormolu looked uniquely promising, by being well-engineered, taking advantage of `ghc-lib`, and having the backing of a major Haskell consultancy. From conversations around 2019/20, I believe I was one of many people who was initially excited about it, then grew frustrated about some of the decisions they made on the minutiae. I still don't actually consider myself to be particularly opinionated about formatting, but there were some deal-breakers, such as trailing commas, and no newlines in import lists.

So [Matt started Fourmolu as a bit of a joke](https://www.reddit.com/r/haskell/comments/gkvpdh/ann_fourmolu/) (although from the start, [some people said they'd actually use it](https://twitter.com/mattoflambda/status/1257155282574049281)), and I happened to be free on the afternoon that he opened some issues asking for help with a few small tasks (#1, #2). I fixed those, then over the next few weeks set about making it possible to use my own personal style, and integrating Fourmolu with HLS. Which meant that by the autumn of 2020, I'd whipped it in to becoming the formatter I'd always wanted (notwithstanding a few small issues like #46 and #78).

In hindsight, this is the point where I found myself lacking much enthusiasm for further development, and would have been a good time to start looking for other maintainers. But I mistakenly assumed that there wouldn't be much work to do to keep the wheels turning. At the end of 2020, Fourmolu was still relatively unknown, the number of GitHub stars and open issues a small fraction of what they are now. I seriously underestimated the enthusiasm the wider community would have for it. Over the next few months, dozens of high-quality PRs and feature requests came flooding in. Meanwhile, I started a new job, moved between cities, the UK began to emerge from lockdown, and my free time for OSS contributions shrunk dramatically. On top of that, I'll admit that this isn't exactly my favourite project to work on. Making edits to a large code base written by someone else is a lot less enticing than working on the latest shiny new idea of my own. Additionally, Fourmolu is unique amongst projects I maintain in that the vast majority of open issues are things I don't personally care about.

So maintenance suffered for a while, and that's how we got in to this mess. But, as mentioned above, I'm fairly confident that we're now out of it. The future is bright! We can hopefully all rest easy knowing that we can continue to live in a world of sane export lists, multi-line haddocks, and slightly-less-indented `where` blocks.
