### ISSUE TITLE
Steal stylish-haskell's import grouping feature

### ISSUE THREAD

**Issue by michaelpj** [fourmolu/fourmolu#297]
`stylish-haskell` has recently acquired a nice feature for [configurably grouping imports](https://github.com/haskell/stylish-haskell/pull/399). It might be nice to steal it.

**Is your feature request specific to Fourmolu?**
- [x] Yes, this feature is not relevant to Ormolu (because it's all about configurability, which ormolu is against)

**Comment by brandonchinn178** [comment]
I swore I opened this issue already, but can't seem to find it. I agree, would be awesome to have this in Fourmolu!

**Comment by georgefst** [comment]
> I swore I opened this issue already, but can't seem to find it.

It was discussed a little in this thread: https://github.com/fourmolu/fourmolu/issues/45.

Anyway, as I said there, I'd _personally_ be happier modifying HLS to support the way I like to group imports, since it has richer knowledge about imports than can be easily passed to Fourmolu. When I do split imports, it's along the lines of qualified v unqualified, or boot library vs Hackage vs local. The latter would be difficult for Fourmolu to manage in full generality by itself. From a glance at the stylish-haskell PR, it seems that it uses a regex-based system which wouldn't capture the former either. But anyway, I'm not totally sure what I want or whether it's feasible. I wouldn't stand in the way of a clone of the stylish-haskell behaviour being implemented here.

**Comment by michivi** [comment]
I was very interested in such a feature, and give it a shot (#403). It's not really like stylish-haskell or as configurable as mentioned in a previous comment. But I wanted to make a simple version first and see if that is compatible with your vision for the feature :slightly_smiling_face:
