### ISSUE TITLE
Add a cli flag to print currently effective options

### ISSUE THREAD

**Issue by jhrcek** [fourmolu/fourmolu#307]
Following up on discussion in https://github.com/fourmolu/fourmolu/issues/306#issuecomment-1489651160
It would be nice if there was a command line flag that you could use to
1. print default configuration file to std out (something like [stylish-haskell](https://github.com/haskell/stylish-haskell#configuration) which allows you to dump default config options to file `stylish-haskell --defaults > .stylish-haskell.yaml`)
This file would contain the default settings + comments showing potential alternatives for each option. I would find it more ergonomic than what I currently do, namely going to github readme and copy-pasting example config into my projects.

2. another potentially useful thing could be to print "currently resolved settings" where you'd see how various defaults get combined with configs from your home (~/fourmolu.yaml) and or from your project (.../your-project/fourmolu.yaml).

Just suggesting potential names for 1 and 2. Feel free to suggest better flag names :smile: 
```bash
fourmolu --default-options
fourmolu --effective-options
```

**Comment by brandonchinn178** [comment]
Makes sense to me! We should generate the default YAML file in `Ormolu.Config.Gen` (using similar logic to the CLI description text for the comments for each option) and just `putStrLn` if we get that flag in `Main.hs`.

Bike-shedding: I think an explicit `fourmolu --print-defaults` would be nice, and maybe `fourmolu --print-config` for the current settings?

PR welcome!

**Comment by brandonchinn178** [comment]
oh interesting. Yeah `--print-defaults` might be simpler, since we already generate `fourmolu.yaml` (containing the ormolu configuration). So it's just a matter of generating another one with the default options and showing it.

`--print-config` is a bit harder because we'd have to add a `ToJSON` instance for `PrinterOptsTotal` (and then we could just do `Yaml.encode`). RE: format, I'd say `--print-config` should just output a YAML file, optionally with comments about provenance (although we don't store that information right now, so let's leave that out for now)

**Comment by georgefst** [comment]
It might be worth updating the title or OP here to reflect what remains to be done after #308 (i.e. `--print-config`).

**Comment by brandonchinn178** [comment]
#337 adds the configuration to the `--debug` flag. Maybe that's good enough for this?

**Comment by brandonchinn178** [comment]
@jhrcek `--debug` now includes the configuration being used. Is that sufficient?

**Comment by jhrcek** [comment]
@brandonchinn178 Thank you, sounds good enough for my purposes :smile:  Feel free to close this issue.
