### ISSUE TITLE
The latest release v0.11.0.0 does't contains 'single-constraint-parens'

### ISSUE THREAD

**Issue by July541** [fourmolu/fourmolu#309]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Describe the bug**
Provide steps to reproduce the bug, and what the expected behavior should be.

The latest release doesn’t contains #304, that means the new introduced config “single-constraint-parens” can’t be rendered properly(my codebases are parened😂).

It would be great to have a patch release to render it.

**Comment by brandonchinn178** [comment]
To be clear, we merged the Ormolu change that had this behavior, cut the release, and only afterwards someone decided they wanted a flag to disable it. This isn't a bug, it's just an ask to cut a new release because you want a new feature. If you absolutely need the cutting edge version, feel free to build from source. It can't be a patch release, because PVP dictates that changing public constructors (as adding a new option does) require a major version bump. We'll release 0.12 at some point, but I can't make promises about when.

I'm a bit confused about your particular situation, though. You said your codebase is "parened", which I assume means it uses parentheses for single constraints. The only purpose of the new single-constraint-parens option is to disable it; 0.11 will always use parentheses. Why do you need this option?

**Comment by July541** [comment]
In order to have the ability to disable paren for single constraints, I need to edit the config. It only possible in the next release(0.12) if I don't compile fourmolu manually?

Honestly, it's not convenient for hls users.

**Comment by brandonchinn178** [comment]
Or stay on 0.10.1.0 for now? Is there a reason you need the upgrade?

**Comment by July541** [comment]
Upgrading HLS with default settings takes me to v0.11🧐

**Comment by brandonchinn178** [comment]
ah I see. I believe the fourmolu plugin for HLS lets you specify a fourmolu executable it'll use instead of the version of fourmolu it ships with.

The next 0.12 version won't help this either, because your version of HLS won't allow 0.12. I believe the best path forward is to just use single-constraint-parens, use the approach I mentioned above to use a separate fourmolu exe, or don't upgrade HLS.

I don't use HLS, so I won't be much help here. @georgefst

**Comment by July541** [comment]
Yes, there seems no alternative solutions until the next HLS release.

**Comment by jhrcek** [comment]
Not sure what editor you're using, but in VSCode it's already possible to configure hls to use fourmolu found on PATH (as opposed to fourmolu library built into hls executable).

![Externa-fourmolu](https://user-images.githubusercontent.com/2716069/229424534-6c03fb49-f39f-402e-9ca5-89c6ce986053.gif)

**Comment by July541** [comment]
@jhrcek Thank you for point it out, I missed this!
