### ISSUE TITLE
Multiline expr starts one column less than Ormolu

### ISSUE THREAD

**Issue by tomjaguarpaw** [fourmolu/fourmolu#428]
**Is your bug specific to Fourmolu?**
- [x] Yes, I've verified that Ormolu does not have this bug

**Did you try it on the web app?**
- [x] Yes, I've verified that https://fourmolu.github.io can reproduce this bug

**Did you search for existing issues?**
- [x] Yes, ~there are no open or closed issues related to my issue~ "ormolu less indentation" throws up nothing obvious

**Describe the bug**

Ormolu formats like this

```.hs
f :: T
f =
  something
    <> ( myFun $
           Just t
       )
```

whereas fourmolu formats like this, with indentation 2:

```.hs
f :: T
f =
  something
    <> ( myFun $
          Just t
       )
```

i.e. `Just` is indented one level less. I've suggested to my team to switch to fourmolu because we don't like the latest Ormolu choice of wrapping singleton constraints in parens, but it seems the amount of churn we'll get by switching to fourmolu is even bigger because of this difference. Is this difference really intended? If so, why?

**Comment by brandonchinn178** [comment]
Yeah, that's kind of expected 🫤 Also see
https://github.com/fourmolu/fourmolu/commit/e9e9ad63dd938868a6fe968c70c592e5cff346b0

The problem is that Fourmolu ensures that a line always begins on a multiple of the indentation, rounding down, which IMO is the better behavior. I thought I had ticketed this in Ormolu, but I can't find it. Let me see what Ormolu says

**Comment by tomjaguarpaw** [comment]
Hmm, OK, I guess this rules out fourmolu for us then :(

**Comment by brandonchinn178** [comment]
More context: https://github.com/fourmolu/fourmolu/pull/37#issuecomment-701733625

This comment is a bit inaccurate, though; it's not at that column because that's where it would've been on the previous line, but because it's a 2-space indentation starting from the expression inside the parentheses:
```hs
f =
  False
    || ( something
           >= other
       )
```

I think really, we want this rule to be "if indentation > 2, indent from parentheses, otherwise indent from the inner expression". Let me take a look...

**Comment by brandonchinn178** [comment]
hm doesn't seem trivial, and for something that's arguably not a big deal... will leave the issue open and punt for now
