### ISSUE TITLE
Feature Request: import stanzas

### ISSUE THREAD

**Issue by ProofOfKeags** [fourmolu/fourmolu#45]
The only thing preventing me from using this at this point is the fact that import reordering does not respect stanzas. This is important for 2 reasons.

1. Internal vs External imports
2. Separating your custom prelude (we all have one) from the rest of your imports.

The idea is maybe to prefix each stanza with some pragma, or infer it from whitespace.

This feature was rejected by the original ormolu team, but maybe this less ~~dogmatic~~ opinionated fork might consider it. It was rejected on the grounds that automatic import insertion would break, but I think it can be made to work if there is a convention around how stanzas get used, and encode common use cases in pragmas.

EDIT: If you use import stanzas in your projects, and you use them differently than the cases I outlined above, I'd love to hear your perspective.

**Comment by georgefst** [comment]
Just to check that we're on the same page first, you should find that since the 0.2 update last week, if using the default settings, Fourmolu does keep newlines between import groups, and only reorders within groups. Are you not finding that to be the case?

**Comment by georgefst** [comment]
I usually use three groups/stanzas:
- Unqualified imports - stuff from `base` and other simple, common, domain-agnostic libraries: `extra`, `mtl`, `pretty-simple` etc. If I'm writing a library to go on Hackage, I'll be a good citizen and restrict this to just boot libraries.
- Qualified imports
- Internal imports (i.e. from the current project). These are always unqualified.

I've been using Fourmolu on my projects, and manually moving around imports is indeed an annoyance. Ideally, I would like it to be HLS, rather than Fourmolu, which has knowledge of the semantics of import stanzas. For one thing, Fourmolu only currently runs GHC's parser, which I imagine is not enough to tell the difference between internal and external modules.

As preliminary steps, I've been meaning to:
- Collect data on the styles of import grouping which are in use across the Haskell community.
- Work out whether HLS' current plugin API makes it possible for a plugin to "intercept" the code action which inserts imports.

**Comment by georgefst** [comment]
As you mentioned in #19, "HLS will insert auto imports immediately under the last import statement in your module". If HLS somehow knew where to insert imports, would this be resolved for your use case?

I'm still not sure what the best approach would be. I wouldn't really want to insert pragmas for this in every file, but trying to infer the meanings of groups could be a bit fragile.

**Comment by brandonchinn178** [comment]
I am currently inclined to close this issue, as the primary thrust of the issue seems to be:

> import reordering does not respect stanzas

which is not true, at least not anymore (it could have been true at one point?).

However, there seems to be a feature request lurking underneath about whether fourmolu could be configured to automatically group imports by some rules. There are a few ways this could be configured:

1. Fourmolu now has the ability to inspect the cabal file (https://github.com/tweag/ormolu/pull/759), so we could find internal modules
2. Modules should be annotated with their package, so we could get this information
3. Plain ol' regex or glob

We could even support all three:
```yaml
# defaults to `null`, which does not regroup imports
group-imports:
  - package: base
  - glob: 'Data.*'
  - regex: '(My)?Prelude'
  - others  # keyword to reference all modules not matched by other groups
  - internal  # keyword to reference all modules in the cabal file
```

However, while Fourmolu does have configurability at the core of its ethos, I personally don't think import groups are worth the additional complexity. I would imagine most people wanting this feature would also want:
* AND/OR rule support
* Rule precedence (e.g. if a module matches both a rule for group 1 and a rule for group 2, which takes precedence?)

At that point, we're basically creating a rules engine within Fourmolu, which seems like a lot.

**Comment by ProofOfKeags** [comment]
> However, there seems to be a feature request lurking underneath about whether fourmolu could be configured to automatically group imports by some rules. There are a few ways this could be configured:

While that would be amazing, I have learned at this point that trying to break up imports is a maintenance burden that doesn't pay for itself with modern tooling like HLS. As the opener of this issue I'm satisfied with closing it. Reopen it later if you change your mind.

**Comment by michaelpj** [comment]
If someone is interested in specifying how to manage import groups, you could take inspiration from this rather nice implementation that might land in `stylish-haskell` soon: https://github.com/haskell/stylish-haskell/pull/399

**Comment by ocharles** [comment]
For other prior art, we wrote https://github.com/circuithub/ch-hs-imports, which gives you stuff like https://github.com/circuithub/ch-hs-imports/blob/master/src/Main.hs#L14
