### ISSUE TITLE
Consistent handling of `do`, `let`, `where`

### ISSUE THREAD

**Issue by AshleyYakeley** [fourmolu/fourmolu#84]
There are a number of possible ways of handling these keywords:

1. sameline/newline
```haskell
alpha = beta where
    gamma = let
        delta = do
            epsilon
        in zeta
```
2. newline-indent/newline-indent
```haskell
alpha = beta
    where
        gamma =
            let
                delta =
                    do
                        epsilon
            in zeta
```
3. newline-half/newline-half
```haskell
alpha = beta
  where
    gamma =
      let
        delta =
          do
            epsilon
      in zeta
```
4. newline-indent/newline
```haskell
alpha = beta
    where
    gamma =
        let
        delta =
            do
            epsilon
        in zeta
```
5. newline-indent/align
```haskell
alpha = beta
    where gamma1 = undefined
          gamma2 =
              let delta1 = undefined
                  delta2 =
                      do epsilon1
                         epsilon2
              in zeta
```
Currently the default behaviour seems to be:
* `do`: sameline/newline
* `let`: newline-indent/align
* `where`: newline-half/newline-half (can be set to newline-indent/newline-indent)

It would be great if there were settings to specify the behaviour of each of these keywords.

**Comment by brandonchinn178** [comment]
As discussed in #155, I don't agree with having a single option that makes all of these consistent. It's also not clear to me why these three constructs, are being discussed in particular. Why not `if`? `let` and `where` both define bindings; how is `do` relevant to how `let` or `where` is styled?

But I would be open to incrementally changing the styles of each of these constructs separately, to allow configuring how `do` blocks are styled / configuring how `let` blocks are styled / etc.

I'm closing this issue, because it doesn't make sense to me to tie these three constructs together. But feel free to open new issues around how `do` and `where` should be configurable (`let` styling will be discussed here: https://github.com/fourmolu/fourmolu/issues/202)
