### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#99]
We've started using CircleCI and it seems to work nicely but I'm mildly concerned by the following:

One massive downside to CircleCI is that it requires users to have a CircleCI account to even see build logs from PRs. IMO this is quite a deterrent to contributions.

_Originally posted by @expipiplus1 in https://github.com/fourmolu/fourmolu/pull/75#issuecomment-855637201_

**Comment by georgefst** [comment]
@expipiplus1 points to the following as a clean, generic Haskell Github actions setup:

https://github.com/Synthetica9/nix-linter/pull/53/commits/cde834e72f2ea5a9c18a7fd10c136f55485a4597

**Comment by brandonchinn178** [comment]
FWIW I don't see that as an issue. You can use your GitHub account to log in to Circle. It's no more a blocker than requiring someone to have a GitHub account to contribute to the project. If I can make a Gitlab account for the sole purpose of filing a GHC bug, I think someone could log in to Circle CI with the same account.

And if the contributor absolutely does not want to make a Circle account, they could always run tests locally, and maintainers can copy/paste the CI error into the PR

**Comment by brandonchinn178** [comment]
FYI the original assertion is not true; I can see this CI run (from another open source project) in an incognito window: https://app.circleci.com/pipelines/github/LeapYear/aeson-schemas/343/workflows/7bad71b5-50d9-40ad-a5c6-8246197feee6

But I ended up moving to GitHub actions anyway, because it made automating releases easier (see #183)
